# site settings
title: Jed Stening
artist: Jed Stening
profession: Art & design
email: jed@stening.co
description: The digital portfolio of Jed Stening, a graphic designer and artist from the UK.
address: "https://stening.co"
baseurl: ""

# build settings
destination: /srv/hosts/dev.omni/www/co.stening
exclude: ["Gemfile", "Gemfile.lock", "README.md", "LICENSE.md", "type/README.md"]
markdown: kramdown
sass:
    sass_dir: styles
    style: compressed

compress_html:
    clippings: all

# non-standard options include
# - artist
# - email
# - address
# - profession
