# site settings
title: Jed Stening
artist: Jed Stening
email: jed@stening.uk
description: The digital portfolio of Jed Stening, a graphic designer and artist from the UK.
address: "http://jedstening.blieque.co.uk"
baseurl: ""

# build settings
exclude: ["type/README.md"]
markdown: kramdown
destination: /srv/hosts/dev.omni/www/uk.stening
sass:
    style: compressed

compress_html:
    clippings: all

# non-standard options include
# - artist
# - email
