# Site settings
title: Jed Stening
artist: Jed Stening
profession: Art & Design
email: jed@stening.co
description: The digital portfolio of Jed Stening, a graphic designer and artist from the UK.
address: "https://stening.co"
baseurl: ""

# Build settings
repository: blieque/stening.co
destination: ./dist
exclude: ["Gemfile", "Gemfile.lock", "README.md", "LICENSE.md", "type/README.md"]
plugins: ["jekyll-coffeescript"]

sass:
    sass_dir: styles
    style: compressed

compress_html:
    clippings: all

# Non-standard options include:
# - artist
# - email
# - address
# - profession
