# site settings
title: Jed Stening
artist: Jed Stening
profession: Art & Design
email: jed@stening.co
description: The digital portfolio of Jed Stening, a graphic designer and artist from the UK.
address: ""
baseurl: "/stening.co"

# build settings
destination: /srv/hosts/dev.omni/www/stening.co
exclude: ["Gemfile", "Gemfile.lock", "README.md", "LICENSE.md", "type/README.md"]
gems: ["jekyll-coffeescript"]

sass:
    sass_dir: styles
    style: compressed

compress_html:
    clippings: all

# non-standard options include
# - artist
# - email
# - address
# - profession
