# site settings
title: Jed Stening
artist: Jed Stening
profession: Art & design
email: himself@blieque.co.uk
description: The digital portfolio of Jed Stening, a graphic designer and artist from the UK.
address: "http://stening.blieque.co.uk"
baseurl: ""

# build settings
destination: /srv/hosts/uk.stening/www
exclude: ["Gemfile", "Gemfile.lock", "README.md", "LICENSE.md", "type/README.md"]
markdown: kramdown
sass:
    sass_dir: styles
    style: compressed

compress_html:
    clippings: all

# non-standard options include
# - artist
# - email
# - address
# - profession
